// Generated by Obsidian Export — Nubien - AI Agency & Studio (copy)
// Page: / · 02/07/2026
import './styles.css'


export default function Page() {
  return (
    <div style={{ background: '#000000', minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
    <div style={{ background: 'rgb(0, 0, 0)', width: '1252px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 70px }}>
        <div style={{ width: '1fr', height: '91px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px, overflow: 'hidden' }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: '1px', overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '200px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ height: '112px', overflow: 'hidden' }} />
        <div style={{ height: '112px', overflow: 'hidden' }} />
        <div style={{ width: '46%', height: '44%', overflow: 'hidden' }} />
        <div style={{ width: '46%', height: '44%', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 28px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ height: '810px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ height: '70%', overflow: 'hidden' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ width: '1fr', height: '700px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: '100px', overflow: 'hidden' }} />
          <div style={{ width: '1276px', height: '1276px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: '1130px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ overflow: 'hidden' }} />
        </div>
        <div style={{ width: '42%', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 34px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden', borderRadius: '0px' }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 24px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 50px, borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '120px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 120px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 80px 60px 80px', display: 'flex', flexDirection: 'column', gap: 60px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '19%', borderRadius: '0%' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', gap: 24px, overflow: 'hidden' }} />
          <div style={{ width: '80%', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 20px }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 120px 0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '100px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '100px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 100px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
            <div style={{ width: '184px', height: '184px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
              <div style={{ width: '184px', height: '184px' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 24px, borderRadius: '0px' }} />
            </div>
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 100px }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 20px 0px', display: 'flex', flexDirection: 'row', gap: 84px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '120px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 120px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ height: '103%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
            <div style={{ height: '101%', overflow: 'hidden' }} />
          </div>
          <div style={{ height: '224px', overflow: 'hidden' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'row', gap: 10px, borderRadius: '30px' }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 120px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '100px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'row', gap: 10px, borderRadius: '30px' }} />
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 120px 80px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }} />
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '120px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 120px 0px 120px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 48px }}>
            <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'row', gap: 10px, borderRadius: '30px' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '120px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 120px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 0px 60px 0px', display: 'flex', flexDirection: 'column', gap: 60px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '21%', borderRadius: '0px' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 70px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 120px 0px 120px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                  <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
                </div>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
              </div>
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '100px 80px 0px 80px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'row', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div style={{ background: 'rgb(0, 0, 0)', width: '810px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 70px }}>
        <div style={{ width: '1fr', height: '91px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px, overflow: 'hidden' }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: '1px', overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '200px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ height: '200px', overflow: 'hidden' }} />
        <div style={{ height: '200px', overflow: 'hidden' }} />
        <div style={{ height: '200px', overflow: 'hidden' }} />
        <div style={{ height: '200px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 28px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ height: '810px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ height: '70%', overflow: 'hidden' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ width: '1fr', height: '657px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: '100px', overflow: 'hidden' }} />
          <div style={{ width: '1276px', height: '1276px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: '1130px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ overflow: 'hidden' }} />
        </div>
        <div style={{ height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 34px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden', borderRadius: '0px' }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', gap: 24px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px, borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '100px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 50px 60px 50px', display: 'flex', flexDirection: 'column', gap: 60px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '19%', borderRadius: '0%' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', gap: 24px, overflow: 'hidden' }} />
          <div style={{ width: '80%', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 20px }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 100px 0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '100px 50px 0px 50px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '100px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 100px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '184px', height: '184px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
              <div style={{ width: '184px', height: '184px' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 24px, borderRadius: '0px' }} />
            </div>
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 100px }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '100px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ height: '103%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
            <div style={{ height: '101%', overflow: 'hidden' }} />
          </div>
          <div style={{ height: '224px', overflow: 'hidden' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 100px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '100px 50px 0px 50px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }} />
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 100px 50px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }} />
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '100px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 48px }}>
            <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '100px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 50px 60px 50px', display: 'flex', flexDirection: 'column', gap: 60px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '21%', borderRadius: '0px' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 70px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 50px 0px 50px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                  <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
                </div>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
              </div>
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '100px 50px 0px 50px', display: 'flex', flexDirection: 'column', gap: 100px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 60px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
        </div>
      </div>
    </div>
    <div style={{ background: 'rgb(0, 0, 0)', width: '390px', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }}>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 70px }}>
        <div style={{ width: '1fr', height: '91px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 38px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 26px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 34px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 12px, overflow: 'hidden' }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: '1px', overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '70px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 70px, overflow: 'hidden' }}>
        <div style={{ height: '100px', overflow: 'hidden' }} />
        <div style={{ height: '100px', overflow: 'hidden' }} />
        <div style={{ width: '150%', height: '100px', overflow: 'hidden' }} />
        <div style={{ width: '150%', height: '100px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 28px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ height: '770px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: '100px' }} />
        <div style={{ width: '110%', height: '70%', overflow: 'hidden' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ width: '1fr', height: '590px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden' }}>
          <div style={{ width: '1fr', height: '50px', overflow: 'hidden' }} />
          <div style={{ width: '870px', height: '870px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: '1130px', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
              <div style={{ width: 'fit-content', height: '100%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 0px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ overflow: 'hidden' }} />
        </div>
        <div style={{ height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 20px 0px 20px', display: 'flex', flexDirection: 'column', gap: 34px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px, overflow: 'hidden' }} />
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 80px 30px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden', borderRadius: '0px' }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }} />
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 40px, borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 10px 0px 10px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 20px 60px 20px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '19%', borderRadius: '0%' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 24px, overflow: 'hidden' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 16px }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 80px 0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '80px 30px 0px 30px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 20px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 20px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 40px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '80px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '184px', height: '100px', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px }}>
              <div style={{ width: '184px', height: '184px' }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 24px, borderRadius: '0px' }} />
            </div>
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 80px }}>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '80px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }}>
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 40px }}>
          <div style={{ height: '103%', padding: '0px', display: 'flex', flexDirection: 'column', gap: 10px, overflow: 'hidden' }}>
            <div style={{ height: '101%', overflow: 'hidden' }} />
          </div>
          <div style={{ height: '224px', overflow: 'hidden' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }} />
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '0px 0px 80px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '80px 30px 0px 30px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }} />
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '70px 30px 80px 30px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }} />
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '120px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 40px, overflow: 'hidden' }}>
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'row', gap: 10px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 80px 30px', display: 'flex', flexDirection: 'column', gap: 48px }}>
            <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '10px', display: 'flex', flexDirection: 'column', gap: 10px, borderRadius: '30px' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px, overflow: 'hidden' }} />
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 32px }} />
            </div>
          </div>
        </div>
      </div>
      <div style={{ width: '1fr', height: 'fit-content', padding: '0px 10px 0px 10px', display: 'flex', flexDirection: 'column', gap: 80px, overflow: 'hidden' }}>
        <div style={{ background: 'rgb(8, 8, 8)', width: '1fr', height: 'fit-content', padding: '100px 20px 60px 20px', display: 'flex', flexDirection: 'column', gap: 70px, overflow: 'hidden', borderRadius: '20px' }}>
          <div style={{ height: '21%', borderRadius: '0px' }} />
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px, overflow: 'hidden' }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 30px 0px 30px', display: 'flex', flexDirection: 'row', gap: 10px }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                  <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
                </div>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }} />
              </div>
            </div>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px 0px 0px 0px', display: 'flex', flexDirection: 'column', gap: 24px, overflow: 'hidden' }} />
          </div>
        </div>
        <div style={{ width: '1fr', height: '1px', borderRadius: '0px' }} />
      </div>
      <div style={{ background: 'rgb(0, 0, 0)', width: '1fr', height: 'fit-content', padding: '80px 30px 0px 30px', display: 'flex', flexDirection: 'column', gap: 70px, overflow: 'hidden' }}>
        <div style={{ opacity: 0.7 }} />
        <div style={{ height: '224px', overflow: 'hidden' }} />
        <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 40px }}>
          <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 50px }}>
            <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px, overflow: 'hidden' }}>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 30px }}>
                <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'column', gap: 3px }} />
              </div>
              <div style={{ width: '1fr', height: 'fit-content', padding: '0px', display: 'flex', flexDirection: 'row', gap: 10px, overflow: 'hidden' }} />
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  )
}
